export const GLOSSARY_CATEGORIES = [
  "Основы",
  "Кластер и репликация",
  "Producer и доставка",
  "Consumer и обработка",
  "Хранение",
] as const;

export type GlossaryCategory = (typeof GLOSSARY_CATEGORIES)[number];

export type GlossaryEntry = {
  term: string;
  aliases: string[];
  category: GlossaryCategory;
  summary: string;
  howItWorks: string;
  example: string;
  qaFocus: string;
};

export const GLOSSARY: GlossaryEntry[] = [
  {
    term: "Record / Event",
    aliases: ["сообщение", "событие", "message", "record"],
    category: "Основы",
    summary: "Единица данных, которую Producer публикует в Kafka, а Consumer читает и обрабатывает. В разговорной речи её часто называют сообщением или событием, хотя в Kafka API используется термин record.",
    howItWorks: "Record содержит value (payload), необязательный key, headers и timestamp. После записи Kafka добавляет к нему служебные координаты — topic, partition и offset; вместе они позволяют точно найти событие в распределённом журнале.",
    example: "OrderCreated с key=order-8421 и JSON-payload попадает в orders.events / P1 / offset 43.",
    qaFocus: "Проверяйте не только payload, но и key, headers, timestamp, выбранную partition и отсутствие неожиданных дублей.",
  },
  {
    term: "Producer",
    aliases: ["продюсер", "отправитель", "publisher"],
    category: "Основы",
    summary: "Клиентское приложение, которое формирует record и публикует его в Kafka. Producer решает, в какой topic и partition отправить данные, а также насколько строгого подтверждения доставки ждать.",
    howItWorks: "Перед отправкой клиент получает metadata кластера, сериализует key и value, выбирает partition, собирает records в batches и направляет Produce request прямо Broker, где находится Leader нужной partition.",
    example: "Application Service публикует событие создания заявки в topic loan.application.created.",
    qaFocus: "Проверяйте сериализацию, routing по key, настройки acks/retries/idempotence и то, как приложение обрабатывает timeout или ошибку Broker.",
  },
  {
    term: "Broker",
    aliases: ["брокер", "kafka server", "сервер Kafka"],
    category: "Основы",
    summary: "Отдельный сервер Kafka, который принимает клиентские запросы и хранит на диске replicas разных partitions. Несколько Brokers вместе образуют Kafka cluster.",
    howItWorks: "Один Broker может быть Leader для одних partitions и Follower для других. При его остановке теряются не сами логические partitions, а размещённые на нём физические replicas; доступность зависит от оставшихся копий и ISR.",
    example: "B1 хранит P0 Leader и P2 Follower, а B2 — P0 Follower и P1 Leader.",
    qaFocus: "При тесте отказа фиксируйте, какие Leader и replicas находились на выключенном Broker, кто стал новым Leader и продолжились ли чтение и запись.",
  },
  {
    term: "Cluster",
    aliases: ["кластер"],
    category: "Основы",
    summary: "Набор Brokers, которые совместно хранят topics, partitions и их replicas. Для клиента кластер выглядит как единая Kafka-система, хотя данные физически распределены по нескольким серверам.",
    howItWorks: "Метаданные кластера описывают Brokers, topics, размещение replicas и текущих Leaders. Контроллер координирует изменения метаданных и выбор новых Leaders при сбоях.",
    example: "Стенд Kafka Path состоит из трёх Brokers: B1, B2 и B3.",
    qaFocus: "Проверяйте поведение не только при полном падении Kafka, но и при частичной деградации: один Broker offline, ISR уменьшился, часть partitions доступна, часть — нет.",
  },
  {
    term: "Topic",
    aliases: ["топик", "поток событий"],
    category: "Основы",
    summary: "Именованный поток records одной предметной области. Topic — логическое понятие: фактически его данные разделены между partitions и размещены в виде replicas на Brokers.",
    howItWorks: "Количество partitions задаёт потенциальный параллелизм и влияет на routing. Конфигурация topic также определяет replication factor, retention, compaction, min.insync.replicas и другие правила хранения.",
    example: "orders.events может содержать OrderCreated, OrderPaid и OrderShipped для разных заказов.",
    qaFocus: "Проверяйте правильное имя topic, права доступа, число partitions, формат событий и соответствие настроек topic требованиям системы.",
  },
  {
    term: "Partition",
    aliases: ["партиция", "раздел", "partition log"],
    category: "Основы",
    summary: "Упорядоченный append-only журнал внутри topic. Kafka гарантирует порядок records только в пределах одной partition, но не устанавливает единый порядок между всеми partitions topic.",
    howItWorks: "Каждый новый record дописывается в конец выбранной partition и получает следующий offset. Разделение topic на несколько partitions позволяет хранить и читать поток параллельно, но делает выбор key важной частью модели данных.",
    example: "created → paid → shipped с одинаковым key попадают в P1 и получают возрастающие offsets 42, 43, 44.",
    qaFocus: "Если бизнес требует порядок по заказу или пользователю, убедитесь, что связанные события получают одинаковый key и действительно идут в одну partition.",
  },
  {
    term: "Key",
    aliases: ["ключ сообщения", "record key", "partition key"],
    category: "Основы",
    summary: "Необязательная часть record, которую Partitioner обычно использует для стабильного выбора partition. Key часто совпадает с бизнес-идентификатором: orderId, userId или applicationId.",
    howItWorks: "При неизменном числе partitions и алгоритме partitioner одинаковый сериализованный key даёт одинаковый результат hash и направляет records в одну partition. После увеличения числа partitions распределение ключей может измениться.",
    example: "key=order-8421 удерживает все изменения заказа в одной P1.",
    qaFocus: "Проверяйте null/пустой key, кодировку и сериализацию ключа, стабильность routing и отсутствие случайного бизнес-ID в payload вместо key.",
  },
  {
    term: "Partitioner",
    aliases: ["партиционер", "routing", "маршрутизация"],
    category: "Основы",
    summary: "Алгоритм Producer, который выбирает partition для нового record. Он может учитывать явно указанную partition, hash от key или распределять records без key между доступными partitions.",
    howItWorks: "Producer выполняет routing до сетевой отправки, используя metadata topic. Пользовательский partitioner может реализовать собственное правило, но неправильная логика способна создать перекос нагрузки или нарушить ожидаемый порядок.",
    example: "hash(order-8421) % 3 → P1 в учебной модели Kafka Path.",
    qaFocus: "Проверяйте детерминированность для одинакового key, распределение множества разных keys и поведение после изменения числа partitions.",
  },
  {
    term: "Offset",
    aliases: ["смещение", "позиция записи"],
    category: "Основы",
    summary: "Монотонно возрастающая позиция record внутри конкретной partition. Offset не является глобальным номером во всём topic: P0/offset 42 и P1/offset 42 — разные записи.",
    howItWorks: "Leader назначает offset при append. После удаления старых сегментов или compaction в журнале могут появляться пропуски, поэтому offset — координата, а не гарантия непрерывной последовательности существующих records.",
    example: "Точная координата события: orders.events / P1 / offset 43.",
    qaFocus: "Сохраняйте topic + partition + offset вместе; одного offset недостаточно для поиска события и расследования дублей.",
  },
  {
    term: "Leader replica",
    aliases: ["лидер", "leader", "лидер-реплика"],
    category: "Кластер и репликация",
    summary: "Активная копия partition, через которую идут все операции записи и обычного чтения этой partition. В каждый момент у partition должен быть один Leader.",
    howItWorks: "Producer и Consumer получают metadata и обращаются к Broker с Leader. Follower replicas копируют выбранный Leader порядок records; при его отказе контроллер может выбрать новый Leader из допустимых синхронных replicas.",
    example: "P0 Leader находится на B1; после остановки B1 роль переходит к P0 replica на B2.",
    qaFocus: "Ищите ситуации без Leader, с недоступным Leader или с двумя ошибочно указанными Leaders в пользовательской топологии.",
  },
  {
    term: "Follower replica",
    aliases: ["фолловер", "ведомая реплика", "follower"],
    category: "Кластер и репликация",
    summary: "Физическая копия той же partition на другом Broker. Follower не принимает запись напрямую от Producer, а забирает records у Leader и воспроизводит тот же порядок.",
    howItWorks: "Follower регулярно fetch-ит новые данные. Пока он достаточно близко к Leader и поддерживает связь, replica входит в ISR; при сильном отставании или отказе она исключается из ISR, но остаётся назначенной replica.",
    example: "P0 Leader на B1, а P0 Follower на B2 хранит резервную копию offsets.",
    qaFocus: "Различайте assigned replica, online replica и ISR: включённый Broker ещё не гарантирует, что его Follower уже синхронизирован.",
  },
  {
    term: "Replication factor (RF)",
    aliases: ["rf", "фактор репликации", "replication.factor"],
    category: "Кластер и репликация",
    summary: "Желаемое число физических replicas каждой partition, включая Leader. RF=3 означает одну Leader replica и ещё две копии на других Brokers.",
    howItWorks: "Replication factor повышает устойчивость к отказам, но увеличивает расход диска и сетевой трафик. RF не может быть больше количества подходящих Brokers, а само наличие назначенных копий не означает, что все они входят в ISR.",
    example: "При RF=2 P1 хранится как Leader на B2 и Follower на B3.",
    qaFocus: "Проверяйте, что replicas размещены на разных Brokers и что требуемая надёжность достигается фактическим ISR, а не только числом RF в конфигурации.",
  },
  {
    term: "ISR",
    aliases: ["in-sync replicas", "синхронные реплики"],
    category: "Кластер и репликация",
    summary: "In-Sync Replicas — динамический набор Leader и Followers, которые Kafka считает достаточно синхронизированными. ISR может быть меньше replication factor и изменяться во время работы.",
    howItWorks: "Leader отслеживает, какие replicas остаются в допустимом отставании. Только подходящая синхронная replica обычно может безопасно стать новым Leader, а acks=all ждёт подтверждения всего текущего ISR.",
    example: "RF=3, но ISR=[B1,B2]: B3 назначен Follower, однако отстаёт и временно исключён.",
    qaFocus: "При сбоях сравнивайте RF, текущий ISR и min.insync.replicas — это три разных величины.",
  },
  {
    term: "min.insync.replicas",
    aliases: ["min isr", "минимальный ISR"],
    category: "Кластер и репликация",
    summary: "Минимальное число replicas в ISR, необходимое для успешной записи, когда Producer использует acks=all. В подсчёт входит Leader.",
    howItWorks: "Если текущий ISR меньше заданного минимума, Kafka отклоняет Produce request ошибкой семейства NotEnoughReplicas. Настройка повышает durability, но снижает доступность записи при деградации кластера.",
    example: "RF=3, min ISR=2, ISR=[B1] → запись с acks=all запрещена.",
    qaFocus: "Проверяйте обе границы: запись проходит при ISR=min ISR и отклоняется при ISR=min ISR−1.",
  },
  {
    term: "Leader election",
    aliases: ["выбор лидера", "failover", "election"],
    category: "Кластер и репликация",
    summary: "Назначение новой Leader replica после отказа текущей или изменения метаданных. В безопасном варианте новый Leader выбирается из синхронных replicas.",
    howItWorks: "Контроллер обнаруживает недоступность Broker, обновляет metadata и назначает подходящую replica. Во время failover partition может быть кратковременно недоступна; Producer обновляет metadata и повторяет запрос согласно своей политике retries.",
    example: "B1 с P0 Leader выключен → синхронная P0 replica на B2 становится Leader.",
    qaFocus: "Проверяйте время восстановления, сохранность committed records, обновление metadata клиентов и последствия уменьшения ISR после election.",
  },
  {
    term: "Catching up",
    aliases: ["догоняющая реплика", "recovery", "catch-up"],
    category: "Кластер и репликация",
    summary: "Состояние replica, которая уже доступна, но ещё не скопировала все необходимые records с Leader. До завершения синхронизации она обычно не входит в ISR.",
    howItWorks: "После запуска Broker Follower сравнивает свой log с Leader, при необходимости обрезает расходящийся хвост и догружает пропущенные batches. Только затем replica может вернуться в ISR и участвовать в подтверждении acks=all.",
    example: "B2 включён, но P0 на нём помечена CATCHING UP; ISR пока остаётся [B1].",
    qaFocus: "Не считайте восстановление завершённым только по статусу Broker=ONLINE — дождитесь возврата нужной replica в ISR.",
  },
  {
    term: "LEO / Log End Offset",
    aliases: ["log end offset", "конец журнала", "leo"],
    category: "Кластер и репликация",
    summary: "Позиция конца локального журнала конкретной replica — offset, с которого будет записан следующий record. У Leader и каждого Follower свой LEO.",
    howItWorks: "Разница между LEO Leader и Follower показывает отставание этой копии. Равные значения сами по себе не заменяют все критерии ISR, но помогают увидеть, успела ли replica получить актуальный хвост журнала.",
    example: "Leader LEO=45, Follower LEO=43 → Follower не хватает двух records.",
    qaFocus: "При recovery наблюдайте, растёт ли LEO Follower и достигает ли он Leader; зависшее значение указывает на проблему репликации.",
  },
  {
    term: "High Watermark / Committed record",
    aliases: ["hw", "high watermark", "committed", "зафиксированная запись"],
    category: "Кластер и репликация",
    summary: "High Watermark отделяет подтверждённую синхронными replicas часть partition от ещё не полностью реплицированного хвоста. Record ниже этой границы считается committed и доступен обычному Consumer.",
    howItWorks: "Leader продвигает границу по мере того, как текущий ISR подтверждает получение данных. Committed не равно «никогда не потеряется при любых обстоятельствах»: гарантия зависит от того, останется ли доступна хотя бы одна актуальная синхронная replica.",
    example: "Leader уже имеет offset 44, но HW=43: новый record пока находится в неподтверждённом хвосте.",
    qaFocus: "Разделяйте факты append, replication, commit и ACK — это разные этапы и разные наблюдаемые состояния.",
  },
  {
    term: "acks",
    aliases: ["ack", "acknowledgment", "подтверждение producer"],
    category: "Producer и доставка",
    summary: "Настройка Producer, определяющая, какое подтверждение нужно получить, прежде чем считать Produce request успешным. Она управляет компромиссом между задержкой, доступностью и durability.",
    howItWorks: "acks=0 не ждёт ответа; acks=1 ждёт append только на Leader; acks=all ждёт подтверждения всего текущего ISR и проверяет min.insync.replicas. acks=all не означает ожидание всех assigned replicas, если часть из них уже вне ISR.",
    example: "При acks=1 Producer видит SUCCESS до того, как Follower успел скопировать record.",
    qaFocus: "Сравнивайте результат Producer с фактическим состоянием partition: SUCCESS, timeout и наличие record — не одно и то же.",
  },
  {
    term: "Retries",
    aliases: ["retry", "повторная отправка", "повторы"],
    category: "Producer и доставка",
    summary: "Повторные попытки Producer после временной ошибки или timeout. Retries повышают шанс доставки, но без idempotence могут создать duplicate или изменить порядок при некоторых конфигурациях.",
    howItWorks: "Producer повторяет Produce request, пока не исчерпан лимит времени/попыток или не получен окончательный результат. Повтор не устраняет причину сбоя: недоступный Leader или недостаточный ISR должны восстановиться отдельно.",
    example: "ACK первой попытки потерян; Producer отправляет тот же event ещё раз.",
    qaFocus: "Проверяйте число attempts, интервалы, итоговую ошибку, количество реально записанных records и сохранение порядка.",
  },
  {
    term: "Idempotence",
    aliases: ["enable.idempotence", "идемпотентный producer", "dedup"],
    category: "Producer и доставка",
    summary: "Механизм Producer и Broker, который не позволяет сетевому retry записать один и тот же record повторно. Он защищает от дублей внутри одной producer session, но не заменяет бизнес-идемпотентность приложения.",
    howItWorks: "Broker отслеживает Producer ID, epoch и sequence numbers. Для явного enable.idempotence=true нужны совместимые настройки: acks=all, retries>0 и допустимый max.in.flight; конфликт приводит к ConfigException.",
    example: "Две сетевые попытки с PID=7 и sequence=12 дают один record и один offset.",
    qaFocus: "Отдельно тестируйте сетевой retry и два независимых вызова бизнес-операции: idempotent Producer решает только первый случай.",
  },
  {
    term: "Producer ID / Epoch / Sequence",
    aliases: ["pid", "producer epoch", "sequence number"],
    category: "Producer и доставка",
    summary: "Служебная идентичность idempotent Producer и порядковые номера его batches. Эта комбинация позволяет Broker отличить ожидаемый следующий batch от сетевого повтора или устаревшего Producer.",
    howItWorks: "Sequence увеличивается для новых данных, но сохраняется при retry того же batch. Epoch меняется при переинициализации Producer и помогает fence-ить старый экземпляр, который больше не должен писать.",
    example: "PID=7, epoch=1, sequence=12 уже записан → повтор с теми же значениями подавляется.",
    qaFocus: "В логах связывайте duplicate suppression с конкретными PID/epoch/sequence, а не только с одинаковым JSON-payload.",
  },
  {
    term: "Duplicate",
    aliases: ["дубль", "повторная запись"],
    category: "Producer и доставка",
    summary: "Дополнительный record, представляющий то же бизнес-событие, но имеющий собственный offset. Дубль часто появляется, когда первая запись успешна, ACK теряется, а retry выполняется без idempotence.",
    howItWorks: "Kafka не сравнивает payload и не понимает бизнес-смысл события. Два одинаковых JSON являются двумя нормальными records, если протокол Producer не распознал их как повтор одного batch.",
    example: "eventId=evt-17 записан на offsets 43 и 44 после потери ACK.",
    qaFocus: "Ищите дубли по стабильному eventId или бизнес-ключу и проверяйте идемпотентность side effect у Consumer.",
  },
  {
    term: "Ambiguous result",
    aliases: ["неопределённый результат", "unknown outcome", "timeout after append"],
    category: "Producer и доставка",
    summary: "Ситуация, когда клиент получил timeout и не может определить, был ли record записан. Ошибка Producer не доказывает отсутствие события в Kafka.",
    howItWorks: "Сбой мог произойти до Broker — тогда записи нет, либо после успешного append — тогда record уже существует, но ACK не дошёл. Повторная отправка разрешает проблему доставки, но без idempotence создаёт риск дубля.",
    example: "Producer вернул TimeoutException, однако event уже находится в P1/offset 43.",
    qaFocus: "После timeout проверяйте topic по eventId, key и временному интервалу, а затем оценивайте последствия retry.",
  },
  {
    term: "At-most-once",
    aliases: ["не более одного раза", "0 или 1"],
    category: "Producer и доставка",
    summary: "Семантика «не более одного раза»: обработка не повторяется, но при сбое событие может быть потеряно. Возможный результат — ноль или одна успешная обработка.",
    howItWorks: "На стороне Consumer такой эффект обычно возникает, если offset фиксируется до бизнес-обработки: при crash после commit повторного чтения не будет. На стороне Producer похожий риск создают acks=0 и отсутствие управляемых retries.",
    example: "Consumer commit-ит offset 44, падает до записи в БД — event больше не будет автоматически прочитан этой группой.",
    qaFocus: "Проверяйте точный момент commit относительно side effect и поведение после crash между этими шагами.",
  },
  {
    term: "At-least-once",
    aliases: ["как минимум один раз", "1 или больше"],
    category: "Producer и доставка",
    summary: "Семантика «как минимум один раз»: система стремится не потерять событие, но при сбое может доставить или обработать его повторно.",
    howItWorks: "Consumer сначала выполняет бизнес-операцию, а затем commit-ит offset. Если он упадёт между этими действиями, после перезапуска record будет прочитан ещё раз; поэтому side effect должен быть идемпотентным.",
    example: "Запись в БД выполнена, commit offset не успел пройти → после restart тот же order обрабатывается повторно.",
    qaFocus: "Инъецируйте crash после side effect и до commit, затем проверяйте отсутствие двойного списания, уведомления или записи.",
  },
  {
    term: "Exactly-once",
    aliases: ["ровно один раз", "eos", "exactly once semantics"],
    category: "Producer и доставка",
    summary: "Гарантия, при которой результат каждой логической операции становится видимым один раз. Idempotent Producer сам по себе даёт защиту от сетевых дублей записи, но не обеспечивает end-to-end exactly-once для внешней БД или API.",
    howItWorks: "Внутри Kafka exactly-once строится на idempotence, transactions и корректном isolation level Consumer. Для внешнего side effect нужны дополнительные паттерны: идемпотентный ключ, outbox/inbox, транзакционная запись или дедупликация.",
    example: "Один Kafka transaction атомарно фиксирует прочитанные offsets и records, произведённые в другой topic.",
    qaFocus: "Уточняйте границу гарантии: только Kafka-to-Kafka или вся бизнес-цепочка до PostgreSQL, SMS и сторонних сервисов.",
  },
  {
    term: "Consumer",
    aliases: ["консюмер", "подписчик", "reader"],
    category: "Consumer и обработка",
    summary: "Клиентское приложение, которое самостоятельно запрашивает records у Leaders назначенных partitions и выполняет бизнес-обработку. Broker не удаляет record сразу после чтения одним Consumer.",
    howItWorks: "Consumer вызывает poll/fetch, получает batches начиная со своей позиции, десериализует данные и двигает текущую position. Отдельный commit сохраняет точку восстановления для всей consumer group.",
    example: "Notification Service читает loan.approved и отправляет клиенту Push.",
    qaFocus: "Проверяйте ошибки десериализации, повторную обработку, commit timing, lag и реакцию на недоступность внешних зависимостей.",
  },
  {
    term: "Consumer group",
    aliases: ["группа консюмеров", "group.id", "consumer group"],
    category: "Consumer и обработка",
    summary: "Несколько Consumers с одинаковым group.id, которые совместно делят partitions подписанного topic. Внутри одной группы каждую partition в один момент читает не более одного Consumer.",
    howItWorks: "Группа масштабирует обработку до числа partitions. Если Consumers больше, чем partitions, часть экземпляров простаивает; другая группа с отдельным group.id читает тот же поток независимо и хранит собственные offsets.",
    example: "Три partitions и два Consumers → один получает две partitions, второй — одну.",
    qaFocus: "Проверяйте распределение при 1, N и N+1 Consumers, независимость разных group.id и сохранение offsets каждой группы.",
  },
  {
    term: "Rebalance",
    aliases: ["ребалансировка", "перераспределение partitions"],
    category: "Consumer и обработка",
    summary: "Перераспределение partitions между участниками consumer group после входа, выхода, сбоя Consumer или изменения подписки. На время перехода обработка части partitions может приостанавливаться.",
    howItWorks: "Координатор группы формирует новое assignment. Consumer должен корректно завершить работу с отозванными partitions и продолжить с committed offsets, иначе возможны паузы, повторная обработка или пропуск локального состояния.",
    example: "Consumer C2 падает → его P1 назначается C1, который продолжает чтение с сохранённого offset.",
    qaFocus: "Проверяйте частые join/leave, долгую обработку, crash во время rebalance и отсутствие параллельной обработки одной partition двумя участниками группы.",
  },
  {
    term: "Consumer position / Committed offset",
    aliases: ["consumer offset", "позиция чтения", "commit offset"],
    category: "Consumer и обработка",
    summary: "Consumer position — текущая позиция конкретного экземпляра во время чтения; committed offset — сохранённая точка восстановления consumer group. Эти значения могут временно различаться.",
    howItWorks: "После fetch position продвигается, даже если обработка ещё не завершена. Commit обычно сохраняет offset следующего record, который группа должна прочитать после restart или rebalance.",
    example: "Обработан offset 43 → commit=44 означает «следующим читать 44».",
    qaFocus: "Уточняйте, какое именно число показывает инструмент, и проверяйте restart до/после commit, а не только успешное чтение.",
  },
  {
    term: "Consumer lag",
    aliases: ["лаг", "отставание consumer", "records lag"],
    category: "Consumer и обработка",
    summary: "Оценка того, насколько Consumer или consumer group отстаёт от конца partition. Обычно lag считают как разницу между Log End Offset и текущей или committed позицией — точная формула зависит от метрики и инструмента.",
    howItWorks: "Lag растёт, когда Producer пишет быстрее, чем Consumer обрабатывает, либо Consumer остановлен. Малый lag не гарантирует успешную бизнес-обработку, если offsets commit-ятся слишком рано.",
    example: "LEO=120, committed offset=100 → committed lag примерно 20 records.",
    qaFocus: "Сопоставляйте lag с throughput, временем обработки, ошибками и commit policy; отдельно проверяйте каждую partition.",
  },
  {
    term: "Range assignor",
    aliases: ["RangeAssignor", "range assignment", "стратегия range"],
    category: "Consumer и обработка",
    summary: "Стратегия распределения, которая рассматривает partitions каждого topic отдельно и выдаёт Consumer непрерывные диапазоны. При нескольких topics это может создавать перекос между участниками.",
    howItWorks: "Partitions и Consumers упорядочиваются, затем каждому участнику назначается соседний диапазон. Первые Consumers получают по одной дополнительной partition, если число partitions не делится на размер группы без остатка.",
    example: "Для P0–P2 и C1–C2 стратегия Range даёт C1: P0,P1 и C2: P2.",
    qaFocus: "Проверяйте непрерывность диапазонов, распределение остатка и перекос при подписке одной группы сразу на несколько topics.",
  },
  {
    term: "Round Robin assignor",
    aliases: ["RoundRobinAssignor", "round robin assignment", "круговое распределение"],
    category: "Consumer и обработка",
    summary: "Стратегия, которая раскладывает упорядоченный список доступных partitions по Consumers по кругу. При одинаковых подписках число назначений обычно различается не более чем на одну partition.",
    howItWorks: "Assignor проходит по partitions и по очереди выдаёт их C1, C2, C3, затем снова C1. В реальном кластере результат зависит от набора topics и подписок каждого участника.",
    example: "Для P0–P2 и C1–C2 стратегия Round Robin даёт C1: P0,P2 и C2: P1.",
    qaFocus: "Проверяйте баланс количества partitions, детерминированность после повторного join и поведение Consumer с отличающимися подписками.",
  },
  {
    term: "Heartbeat / session timeout",
    aliases: ["heartbeat", "session.timeout.ms", "сердцебиение consumer", "таймаут сессии"],
    category: "Consumer и обработка",
    summary: "Heartbeat сообщает coordinator, что Consumer остаётся живым участником группы. Если heartbeat не приходит дольше session timeout, участник считается недоступным и его partitions переназначаются.",
    howItWorks: "Consumer периодически подтверждает членство в группе. После превышения session timeout coordinator удаляет его из актуального membership и инициирует rebalance; конкретные настройки зависят от используемого consumer group protocol.",
    example: "C2 перестал отправлять heartbeat → через сжатые 5 секунд лаборатории coordinator исключает C2 и передаёт его P1 другому Consumer.",
    qaFocus: "Отдельно моделируйте потерю heartbeat, сетевую задержку и корректное восстановление; не путайте session timeout с долгой бизнес-обработкой между poll().",
  },
  {
    term: "poll() / max.poll.interval.ms",
    aliases: ["poll", "max poll interval", "max.poll.interval.ms", "интервал poll"],
    category: "Consumer и обработка",
    summary: "poll() получает records и поддерживает цикл обработки Consumer. max.poll.interval.ms ограничивает максимальную паузу между вызовами poll при управлении группой.",
    howItWorks: "Если приложение слишком долго обрабатывает batch и не вызывает poll до истечения интервала, Consumer считается неспособным продолжать обработку; группа выполняет rebalance, чтобы передать partitions другому участнику.",
    example: "C1 продолжает отправлять heartbeat, но poll() остановлен на 7 секунд → лаборатория исключает его по max.poll.interval.ms.",
    qaFocus: "Проверяйте большие batches, медленный внешний API, блокировки и соответствие max.poll.records реальному времени обработки до следующего poll.",
  },
  {
    term: "Auto commit / Manual commit",
    aliases: ["enable.auto.commit", "auto commit", "manual commit", "commitSync", "commitAsync"],
    category: "Consumer и обработка",
    summary: "Два подхода к сохранению точки восстановления группы. Auto commit периодически фиксирует позицию автоматически, а manual commit позволяет приложению выбирать момент после нужной стадии обработки.",
    howItWorks: "Commit сохраняет не сам факт успешного бизнес-результата, а offset следующего record для group.id/topic/partition. Слишком ранний commit повышает риск пропуска после crash, слишком поздний — повторной обработки.",
    example: "Position P1=47, committed=44: три records уже получены, но при manual commit после rebalance чтение возобновится с 44.",
    qaFocus: "Инъецируйте сбой до обработки, после side effect и до commit; сравнивайте потери и дубли, а не только итоговый lag.",
  },
  {
    term: "Deserialization",
    aliases: ["десериализация", "decode", "schema"],
    category: "Consumer и обработка",
    summary: "Преобразование bytes из Kafka record в объект приложения: JSON, Avro, Protobuf или другой формат. Ошибка на этом шаге возникает до основной бизнес-логики Consumer.",
    howItWorks: "Deserializer использует ожидаемые типы, кодировку и иногда schema/version. Несовместимое изменение контракта, повреждённый payload или отсутствующее обязательное поле может остановить обработку partition в зависимости от error handling.",
    example: "Consumer ожидает orderId:number, но получает строку или невалидный JSON.",
    qaFocus: "Проверяйте backward/forward compatibility, неизвестные поля, null, неверный content-type и маршрут ошибочного record в retry/DLQ.",
  },
  {
    term: "Side effect",
    aliases: ["побочный эффект", "результат обработки", "external effect"],
    category: "Consumer и обработка",
    summary: "Наблюдаемое изменение вне чтения Kafka: запись в БД, отправка SMS, вызов API, создание файла или публикация нового события. Именно side effect обычно представляет бизнес-результат обработки.",
    howItWorks: "Kafka управляет record и offset, но не знает, успешно ли внешний эффект завершился. Сбой между side effect и offset commit создаёт центральную проблему at-least-once: повторное чтение может повторить бизнес-операцию.",
    example: "Notification Consumer отправил SMS, но упал до commit offset.",
    qaFocus: "Проверяйте идемпотентный бизнес-ключ, транзакционные границы и поведение при частичном успехе внешней системы.",
  },
  {
    term: "__consumer_offsets",
    aliases: ["internal offsets topic", "внутренний топик offsets"],
    category: "Consumer и обработка",
    summary: "Внутренний compacted topic Kafka, где хранятся committed offsets consumer groups и связанные служебные данные управления группами.",
    howItWorks: "Запись связывает group.id, topic и partition с сохранённой позицией. Log compaction оставляет актуальное значение ключа, поэтому Kafka может восстановить точку чтения группы после restart или rebalance.",
    example: "sandbox-cg / orders.events / P1 → committed offset 44.",
    qaFocus: "В прикладных тестах обычно используйте consumer-group инструменты и API, а не редактируйте внутренний topic напрямую.",
  },
  {
    term: "Log segment",
    aliases: ["сегмент", "segment", "файл сегмента"],
    category: "Хранение",
    summary: "Часть журнала partition на диске Broker. Большая partition разбивается на несколько сегментов, чтобы Kafka могла эффективно читать, индексировать и удалять старые данные целыми файлами.",
    howItWorks: "Активный сегмент принимает новые appends; после достижения лимита размера или времени Kafka создаёт следующий. Имя сегмента основано на base offset — первом offset, относящемся к этому диапазону.",
    example: "00000000000000000042.log начинается с base offset 42.",
    qaFocus: "При проверке retention учитывайте, что удаление происходит сегментами, а не мгновенно для каждого отдельного record.",
  },
  {
    term: ".log",
    aliases: ["data file", "файл данных", "segment log"],
    category: "Хранение",
    summary: "Основной файл сегмента, содержащий record batches и сами bytes key, headers и payload. Records располагаются последовательно в порядке append этой partition.",
    howItWorks: "Broker дописывает batches в конец активного .log. Для чтения по offset он сначала находит нужный сегмент и примерную byte position через индекс, затем последовательно сканирует данные.",
    example: "Offset 43 находится внутри segment .log примерно с byte position 512 B.",
    qaFocus: "В реальной диагностике не редактируйте .log вручную; используйте Kafka API и штатные dump/inspection инструменты.",
  },
  {
    term: ".index",
    aliases: ["offset index", "индекс offset", "position index"],
    category: "Хранение",
    summary: "Разреженный индекс, который связывает relative offset с byte position внутри соответствующего .log. Он ускоряет поиск, но не содержит полноценной строки на каждый record.",
    howItWorks: "Kafka находит ближайшую индексную точку, переходит по указанной позиции в .log и дочитывает записи до нужного offset. Relative offset отсчитывается от base offset сегмента.",
    example: "+1 → 512 B означает: record около base offset+1 искать начиная с позиции 512 B.",
    qaFocus: "Не путайте offset record с byte position файла — это разные координаты, которые симулятор показывает отдельно.",
  },
  {
    term: ".timeindex",
    aliases: ["time index", "временной индекс", "timestamp index"],
    category: "Хранение",
    summary: "Разреженный индекс соответствия timestamp → relative offset. Он помогает Kafka приблизительно найти место в журнале, с которого начинается нужный временной диапазон.",
    howItWorks: "По timestamp выбирается ближайшая индексная точка и offset, затем .index и .log используются для точного чтения. Результат зависит от типа record timestamp и не является отдельной базой всех времён событий.",
    example: "12:30:05 → offset 43 → .index → byte position в .log.",
    qaFocus: "При поиске по времени учитывайте CreateTime/LogAppendTime, часовой пояс интерфейса и то, что индекс разреженный.",
  },
  {
    term: "Retention",
    aliases: ["ретеншн", "срок хранения", "retention.ms", "retention.bytes"],
    category: "Хранение",
    summary: "Политика хранения, определяющая, как долго или до какого размера Kafka сохраняет log segments при cleanup.policy=delete. Чтение Consumer не удаляет record немедленно.",
    howItWorks: "Сегмент становится кандидатом на удаление по времени или размеру согласно конфигурации и периодической проверке Broker. Поэтому фактическое удаление может произойти позже порога и затронуть сразу диапазон offsets.",
    example: "retention.ms=7 дней позволяет новой consumer group перечитать недельную историю, если сегменты ещё доступны.",
    qaFocus: "Проверяйте настройки на уровне Broker и topic, время сегментов, задержку фоновой очистки и поведение Consumer при OffsetOutOfRange.",
  },
  {
    term: "Log compaction",
    aliases: ["compaction", "компакция", "cleanup.policy=compact"],
    category: "Хранение",
    summary: "Политика очистки, сохраняющая как минимум последнее известное значение для каждого key в пределах partition. Она полезна для восстановления состояния, но не превращает topic в обычную таблицу БД.",
    howItWorks: "Фоновый cleaner удаляет устаревшие версии одного key из старых сегментов; tombstone с null value обозначает удаление ключа. Compaction асинхронна, поэтому некоторое время в журнале могут существовать несколько версий.",
    example: "Для key=order-8421 остаётся последнее состояние shipped, а старые created/paid со временем очищаются.",
    qaFocus: "Проверяйте стабильность key, tombstones, задержку compaction и способность Consumer восстановить корректное итоговое состояние.",
  },
];
